# Numpy Arrays

In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]

In [3]:
type(mylist)

list

In [4]:
np.array(mylist)

array([1, 2, 3])

In [5]:
mylist

[1, 2, 3]

In [6]:
my_matrix = [[1,2,3], [4,5,6], [7,8,9]]

In [7]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0,101,20)

array([  0,  20,  40,  60,  80, 100])

In [23]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [20]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [21]:
np.random.rand(5,2)

array([[0.5604819 , 0.95669201],
       [0.82726415, 0.60491556],
       [0.88863447, 0.93748634],
       [0.22430359, 0.8375503 ],
       [0.47058393, 0.88492115]])

In [24]:
np.random.randn(5,2)

array([[ 1.16182598, -0.45658449],
       [-1.14480884,  0.67790887],
       [-0.17648326, -2.09779049],
       [-2.27203331, -1.40287316],
       [ 0.18078843, -0.16772993]])

In [25]:
np.random.randint(0,101,(5,2))

array([[ 53,   3],
       [  7,  20],
       [ 70,  85],
       [  4,  76],
       [ 64, 100]])

In [26]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [30]:
arr = np.arange(0,25)
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [31]:
ranarr = np.random.randint(0,101,10)

In [32]:
ranarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [33]:
ranarr.max()

99

In [34]:
ranarr.min()

2

In [35]:
ranarr.argmax()

5

In [36]:
ranarr.argmin()

7